[build]
  publish = "."
  command = "echo 'Static site - no build needed'"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Enable Netlify Identity for password protection
[build.environment]
  NETLIFY_IDENTITY = "true"

# Password protection for admin area
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
