# Decap CMS (formerly NetlifyCMS) Configuration for El Corazón Restaurant
# This file enables a user-friendly admin interface for editing content

# Backend configuration - using git-gateway for Netlify Identity
backend:
  name: git-gateway  # Uses Netlify Identity + Git Gateway (not deprecated, still supported)
  branch: main       # Git branch to commit changes to

# Media storage configuration
media_folder: "images"        # Folder where uploaded images are stored
public_folder: "/images"      # Public URL path for accessing images

# Collections define the content types users can edit
collections:
  # Restaurant Information - Single file collection
  - name: "restaurant"
    label: "Restaurant Info"
    files:
      - file: "content/restaurant.md"
        label: "Restaurant Details"
        name: "restaurant"
        fields:
          - {label: "Restaurant Name", name: "name", widget: "string"}
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "Hero Background Image", name: "hero_image", widget: "image"}
          - {label: "About Text", name: "about_text", widget: "text"}
          - {label: "About Image 1", name: "about_image_1", widget: "image"}
          - {label: "About Image 2", name: "about_image_2", widget: "image"}

  # Menu Items - Folder collection (allows creating new menu items)
  - name: "menu"
    label: "Menu Items"
    folder: "content/menu"     # Folder where menu items are stored
    create: true               # Allow creating new menu items
    slug: "{{slug}}"           # Use slug as filename
    fields:
      - {label: "Category", name: "category", widget: "select", options: ["Appetizers", "Main Courses", "Desserts", "Beverages"]}
      - {label: "Dish Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}

  # Gallery Images - Folder collection (allows creating new gallery items)
  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"  # Folder where gallery items are stored
    create: true               # Allow creating new gallery items
    slug: "{{slug}}"           # Use slug as filename
    fields:
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Caption", name: "caption", widget: "string", required: false}

  # Contact Information - Single file collection
  - name: "contact"
    label: "Contact Info"
    files:
      - file: "content/contact.md"
        label: "Contact Details"
        name: "contact"
        fields:
          - {label: "Address", name: "address", widget: "text"}
          - {label: "Phone", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Hours", name: "hours", widget: "text"}
          - {label: "Google Maps Link", name: "maps_link", widget: "string"}

  # Social Media Links - Single file collection
  - name: "social"
    label: "Social Media"
    files:
      - file: "content/social.md"
        label: "Social Links"
        name: "social"
        fields:
          - {label: "Facebook", name: "facebook", widget: "string", required: false}
          - {label: "Instagram", name: "instagram", widget: "string", required: false}
          - {label: "Twitter", name: "twitter", widget: "string", required: false}
          - {label: "Yelp", name: "yelp", widget: "string", required: false}