# NetlifyCMS Configuration for El Corazón Restaurant
# This file enables a user-friendly admin interface for editing content

backend:
  name: netlify
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  # Restaurant Information
  - name: "restaurant"
    label: "Restaurant Info"
    files:
      - file: "content/restaurant.md"
        label: "Restaurant Details"
        name: "restaurant"
        fields:
          - {label: "Restaurant Name", name: "name", widget: "string"}
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "Hero Background Image", name: "hero_image", widget: "image"}
          - {label: "About Text", name: "about_text", widget: "text"}
          - {label: "About Image 1", name: "about_image_1", widget: "image"}
          - {label: "About Image 2", name: "about_image_2", widget: "image"}

  # Menu Items
  - name: "menu"
    label: "Menu Items"
    folder: "content/menu"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Category", name: "category", widget: "select", options: ["Appetizers", "Main Courses", "Desserts", "Beverages"]}
      - {label: "Dish Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}

  # Gallery Images
  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Caption", name: "caption", widget: "string", required: false}

  # Contact Information
  - name: "contact"
    label: "Contact Info"
    files:
      - file: "content/contact.md"
        label: "Contact Details"
        name: "contact"
        fields:
          - {label: "Address", name: "address", widget: "text"}
          - {label: "Phone", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Hours", name: "hours", widget: "text"}
          - {label: "Google Maps Link", name: "maps_link", widget: "string"}

  # Social Media Links
  - name: "social"
    label: "Social Media"
    files:
      - file: "content/social.md"
        label: "Social Links"
        name: "social"
        fields:
          - {label: "Facebook", name: "facebook", widget: "string", required: false}
          - {label: "Instagram", name: "instagram", widget: "string", required: false}
          - {label: "Twitter", name: "twitter", widget: "string", required: false}
          - {label: "Yelp", name: "yelp", widget: "string", required: false}