backend:
  name: github
  repo: htrillo95/mexican-restaurant-site
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  # Restaurant Information
  - name: "restaurant"
    label: "Restaurant Info"
    files:
      - file: "content/restaurant.md"
        label: "Restaurant Details"
        name: "restaurant"
        fields:
          - {label: "Restaurant Name", name: "name", widget: "string", default: "El Corazón", hint: "Main restaurant name. Keep short and consistent (e.g., 'El Corazón')."}
          - {label: "Tagline", name: "tagline", widget: "string", hint: "A short one-sentence phrase. Example: 'Authentic Mexican cuisine from the heart.'"}
          - {label: "Hero Background Image", name: "hero_image", widget: "image", hint: "Upload a wide photo (min 1200px width). This shows at the top of the homepage."}
          - {label: "About Text", name: "about_text", widget: "text", hint: "Write 2–3 short paragraphs. Keep it conversational, no special formatting."}
          - {label: "About Image 1", name: "about_image_1", widget: "image", hint: "Portrait or square photo. Appears alongside About text."}
          - {label: "About Image 2", name: "about_image_2", widget: "image", hint: "Second supporting photo for the About section."}

  # Menu Items
  - name: "menu"
    label: "Menu Items"
    folder: "content/menu"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Category", name: "category", widget: "select", options: ["Appetizers", "Main Courses", "Desserts", "Beverages"], hint: "Choose which section this dish belongs in."}
      - {label: "Dish Name", name: "name", widget: "string", hint: "Keep it short (e.g., 'Tacos al Pastor')."}
      - {label: "Description", name: "description", widget: "text", hint: "1–3 sentences. Describe the dish and key ingredients."}
      - {label: "Price", name: "price", widget: "string", hint: "Format as number only (e.g., 12.99). The site adds $ automatically."}
      - {label: "Image", name: "image", widget: "image", required: false, hint: "Optional. Upload a clear photo of the dish."}

  # Gallery
  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Image", name: "image", widget: "image", hint: "Upload a photo. Landscape (wide) images look best."}
      - {label: "Caption", name: "caption", widget: "string", required: false, hint: "Optional. A short caption for the image (e.g., 'Fresh margaritas')."}

  # Contact Information
  - name: "contact"
    label: "Contact Info"
    files:
      - file: "content/contact.md"
        label: "Contact Details"
        name: "contact"
        fields:
          - {label: "Address", name: "address", widget: "text", hint: "Format like: '123 Main St, Philadelphia, PA 19104'."}
          - {label: "Phone", name: "phone", widget: "string", hint: "Include area code (e.g., '(215) 555-1234')."}
          - {label: "Email", name: "email", widget: "string", hint: "Business email address (e.g., 'info@elcorazon.com')."}
          - {label: "Hours", name: "hours", widget: "text", hint: "Format each line like: 'Mon–Fri: 11am – 9pm'."}
          - {label: "Google Maps Link", name: "maps_link", widget: "string", hint: "Paste full Google Maps URL for the restaurant location."}

  # Social Media
  - name: "social"
    label: "Social Media"
    files:
      - file: "content/social.md"
        label: "Social Links"
        name: "social"
        fields:
          - {label: "Facebook", name: "facebook", widget: "string", required: false, hint: "Paste full URL (e.g., 'https://facebook.com/elcorazon')."}
          - {label: "Instagram", name: "instagram", widget: "string", required: false, hint: "Paste full URL (e.g., 'https://instagram.com/elcorazon')."}
          - {label: "Twitter", name: "twitter", widget: "string", required: false, hint: "Paste full URL (e.g., 'https://twitter.com/elcorazon')."}
          - {label: "Yelp", name: "yelp", widget: "string", required: false, hint: "Paste full URL (e.g., 'https://yelp.com/biz/elcorazon')."}